command:
  - python
  - -u
  - -m
  - torch.distributed.launch
  - --nproc_per_node=1
  - main.py
  - --distributed
  - --num-gpus=1
  - --mode=train
  - --config-yml=configs/s2ef/2M/schnet/schnet.yml
early_terminate:
  eta: 3
  max_iter: 50
  s: 2
  type: hyperband
method: random
metric:
  goal: minimize
  name: mae
parameters:
  batch_size: 
    values: [8, 16]
