includes:
- configs/is2re/10k/base.yml

model:
  name: allegro
  cutoff: 6.0
  use_pbc: True
  config_path: 'allegro/allegro_energy_config.yaml'
  regress_forces: False

logger: wandb

optim:
  batch_size: 16
  eval_batch_size: 16
  eval_every: 6250
  num_workers: 3
  lr_initial: 0.002
  ema_decay: 0.99


  max_epochs: 30

  scheduler: ReduceLROnPlateau
  mode: min
  factor: 0.8
  patience: 5


  optimizer: Adam
  optimizer_params:
    amsgrad: false
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    weight_decay: 0.