trainer: structure

dataset:
  - src: /scratch/ocp_data/train/data.lmdb
    normalize_labels: False
    target_mean: -1.525913953781128
    target_std: 2.279365062713623
  - src: /scratch/ocp_data/val_id/data.lmdb

logger: wandb

task:
  dataset: single_point_lmdb
  description: "Relaxed state energy prediction from initial structure."
  type: regression
  metric: mae
  labels:
    - relaxed energy
